name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Compile
      shell: bash
      run: | 
        sudo apt update
        
        sudo apt install libmicrohttpd-dev
        
        PROJECT_ROOT=${pwd}
        METRICS_DIR="$PROJECT_ROOT/submodules/metrics"
        
        cd "$METRICS_DIR/lib"
        make
        
        cd "$METRICS_DIR/lib/prom"
        mkdir build
        cd "$METRICS_DIR/lib/prom/build"
        cmake ..
        make
        sudo make install
        
        cd "$METRICS_DIR/lib/promhttp"
        mkdir build
        cd "$METRICS_DIR/lib/promhttp/build"
        cmake ..
        make
        sudo make install
        
        cd "$METRICS_DIR"
        mkdir build
        cd "$METRICS_DIR/build"
        cmake ..
        make all
        
        cd "$PROJECT_ROOT"
        pip install conan
        conan profile detect --force
        conan config home
        mkdir build
        conan install . --build=missing
        cd "$PROJECT_ROOT/build"
        cmake ..
        make
