name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Compile
      shell: bash
      run: | 
        sudo apt install libmicrohttpd-dev
        
        git submodule update --init --recursive
        
        PROJECT_ROOT=$(pwd)
        METRICS_DIR="$PROJECT_ROOT/submodule"
        
        cd "$METRICS_DIR/lib"
        make
        
        cd "$METRICS_DIR/lib/prom"
        mkdir -p build
        cd "$METRICS_DIR/lib/prom/build"
        cmake ..
        make
        sudo make install
        
        cd "$METRICS_DIR/lib/promhttp"
        mkdir -p build
        cd "$METRICS_DIR/lib/promhttp/build"
        cmake ..
        make
        sudo make install
        
        cd "$METRICS_DIR"
        mkdir -p build
        cd "$METRICS_DIR/build"
        cmake ..
        make all
        
        cd "$PROJECT_ROOT"
        pip install conan
        conan profile detect --force
        conan config home
        cp ~/.conan2/profiles/default ~/.conan2/profiles/debug && sed -i -e 's/Release/Debug/g' ~/.conan2/profiles/debug
        mkdir -p build
        conan install . --build=missing --profile=debug
        cd "$PROJECT_ROOT/build"
        cmake .. -DCMAKE_TOOLCHAIN_FILE=./Debug/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_COVERAGE=1
        make
