name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Compile
      shell: bash
      run: | 
        sudo apt update
        
        sudo apt install libmicrohttpd-dev
        
        git submodule update --init --recursive
        
        PROJECT_ROOT=$(pwd)
        METRICS_DIR="$PROJECT_ROOT/submodule"
        
        cd "$METRICS_DIR/lib"
        make
        
        cd "$METRICS_DIR/lib/prom"
        mkdir -p build
        cd "$METRICS_DIR/lib/prom/build"
        cmake ..
        make
        sudo make install
        
        cd "$METRICS_DIR/lib/promhttp"
        mkdir -p build
        cd "$METRICS_DIR/lib/promhttp/build"
        cmake ..
        make
        sudo make install
        
        cd "$METRICS_DIR"
        mkdir -p build
        cd "$METRICS_DIR/build"
        cmake ..
        make all
        
        cd "$PROJECT_ROOT"
        pip install conan
        conan profile detect
        mkdir -p build
        conan install . --build=missing
        cd "$PROJECT_ROOT/build"
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
