My Project: include/cmd_utils.h File Reference
cmd_utils.h File Reference
Commands utilities declaration.
#include <string.h>
#include <stdbool.h>
Macros
#define LOWEST_ARR_INDEX 0
Lowest array index.
Functions
bool is_background_exec (char **tokens)
Checks for "&" existence at the end of the command, "removing" it from the tokens array.
void cleanse_newline (char *input)
If the arg has a newline at its end, it gets wiped. Modifies the arg.
void cleanse_ampersand (char *input)
This function doesn't check for valid arg, it expects a valid string with " &" at the end, aka is_background_exec() returning true.
char * get_possible_redirection (char **argv, bool _stdin)
From a list of tokenized argv strings, check if stdin redirection is found and if it does, return the file.
void cleanse_redirections_on_argv (char **argv)
As redirections are expected at the end of the single command, clean them from argv.
void cleanse_redirections_on_sc (char *sc)
Cleanse redirection on single command, non-tokenized.
Detailed Description
Commands utilities declaration.
Definition in file cmd_utils.h.
Function Documentation
cleanse_ampersand()
void cleanse_ampersand (char * input)
This function doesn't check for valid arg, it expects a valid string with " &" at the end, aka is_background_exec() returning true.
Parameters
input String to cleanse.
Definition at line 34 of file cmd_utils.c.
Referenced by execute_cd(), and execute_echo().
cleanse_newline()
void cleanse_newline (char * input)
If the arg has a newline at its end, it gets wiped. Modifies the arg.
Parameters
input String to cleanse.
Definition at line 25 of file cmd_utils.c.
Referenced by execute_command().
cleanse_redirections_on_argv()
void cleanse_redirections_on_argv (char ** argv)
As redirections are expected at the end of the single command, clean them from argv.
Parameters
argv Tokenized list of strings. Could get modified.
Definition at line 53 of file cmd_utils.c.
References LOWEST_ARR_INDEX.
Referenced by execute_command().
cleanse_redirections_on_sc()
void cleanse_redirections_on_sc (char * sc)
Cleanse redirection on single command, non-tokenized.
Parameters
sc Raw single command. Could modify it.
Definition at line 65 of file cmd_utils.c.
Referenced by execute_command().
get_possible_redirection()
char* get_possible_redirection (char ** argv, bool _stdin)
From a list of tokenized argv strings, check if stdin redirection is found and if it does, return the file.
Parameters
argv Tokenized list of strings.
_stdin Pass true if you're looking for a stdin redirection, false for a stdout redirection.
Returns
The file name, if found; otherwise returns NULL.
Definition at line 40 of file cmd_utils.c.
References LOWEST_ARR_INDEX.
Referenced by execute_command().
is_background_exec()
bool is_background_exec (char ** tokens)
Checks for "&" existence at the end of the command, "removing" it from the tokens array.
Parameters
tokens Array where elements are each token of a single command. After the last useful token, must be a NULL value.
Returns
true if a background execution was called, false otherwise.
Definition at line 8 of file cmd_utils.c.
References LOWEST_ARR_INDEX.
Referenced by execute_command().