My Project: include/shell.h File Reference
shell.h File Reference
Custom shell related logic declaration.
#include "cmd_utils.h"
#include "metrics_utils.h"
#include <stdlib.h>
#include <unistd.h>
#include <linux/limits.h>
#include <limits.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <getopt.h>
#include <errno.h>
#include <wait.h>
#include <signal.h>
#include <fcntl.h>
#include <time.h>
Macros
#define ENV_USER_KEY "USER"
Environment variable key to retrieve the computer current user.
#define SC_TOKEN_SEPARATOR "|"
First layer separator of smybols/tokens/words on a shell command, that creates single commands.
#define TOKEN_SEPARATOR " "
Char or group of chars that define the separation of smybols/tokens/words on a single command.
#define LOWEST_ARR_INDEX 0
Lowest array index.
#define ENV_OLDPWD_KEY "OLDPWD"
Environment variable key to retrieve the last ("old") current working directory.
#define ENV_PWD_KEY "PWD"
Environment variable key to retrieve the current working directory.
#define TERMINAL_FLUSH_DELAY 30000
Average delay that some terminals (in IDEs, Shells, etc.) take to flush stdout/stderr, in microseconds.
#define CLR_ANSI_EC "\033[H\033[J"
ANSI escape codes that moves the cursor to the home position and clears the screen.
#define MAX_TOKENS_PER_COMMAND 32
This shell has a max limit of tokens per command.
#define N_SINGALS_TO_HANDLE 4
Amount of signals to handle, has direct relationship with the signals array.
#define MAX_SINGLE_COMMANDS (ARG_MAX / 4)
Maximum number of single commands to execute, given the max length allowed for an absolute command.
#define METRICS_APP_PATH "/opt/metrics"
Path to the metrics (lab #1) app.
#define METRICS_GET_STATUS_CODE 7
A code, that the "metrics" app understands as "get status".
#define WAIT_T_FOR_METRICS_RESPONSE 3.0
Seconds awaited to receive response from metrics app after a "get status" req, when executed in foreground.
#define G_STATUS_N_METRICS_TRACKED 4
Number of metrics returned by a "get status" by the metrics app.
Functions
void start_shell_ml (void)
Starts the custom shell main loop.
char ** tokenize_single_command (char *sc)
Passed a single command, tokenize it, and return an array with each token.
void execute_command (char *input, char *cwd)
Executes certain command, could be an internal one, external one, or unexistent.
void execute_batch_file (const char *path)
Tries to execute a certain (no comments, one line per command) batch file.
int redirect_stdin (const char *file_name)
Redirects the stdin to a specific existent (hopefully) file.
int redirect_stdout (const char *file_name)
Redirects the stdout to a specific existent or inexistent (will get created) file.
void restore_stdio (int original_stdio, int target_fd)
Restores stdin to its original fd for the current process.
void execute_cd (char *input, char **sc_tokens, bool background_execution, char *cwd)
"Change directory" internal command.
void execute_echo (char *input, char **sc_tokens, bool background_execution)
"Echo" internal command.
void execute_stop_monitor (int *metrics_pid)
Executes the "stop_monitor" command, which stops the "metrics" app, if it was init by this Shell.
void execute_status_monitor (const int *metrics_pid)
Executes the "status_monitor" command, that shows the "metrics" app, if it was init by this Shell.
void execute_external_cmd (char **sc_tokens, bool background_execution)
Potential external command execution.
void handle_sigusr1 (int sig, siginfo_t *info, void *context)
You don't call this function directly, this is a handler.
void _wstderr (const char *s, bool use_perror)
Monkeypatch of perror and fprintf(stderr, ...). Needed due to "bad" management of some IDE/Shell terminals.
void _free_recursively (void **arr, int limit)
Auxiliary function to free dinamycally allocated memory recursively.
Variables
static const int signals [4] = {SIGINT, SIGTERM, SIGTSTP, SIGQUIT}
Signals handled or not, depending on the process currently executed.
Detailed Description
Custom shell related logic declaration.
Definition in file shell.h.
Function Documentation
_free_recursively()
void _free_recursively (void ** arr, int limit)
Auxiliary function to free dinamycally allocated memory recursively.
Parameters
arr Array of array. Could be for example an array of strings (char array).
limit The limit at which stop to free elements of the upmost array. Pass -1 as the limit to free until a NULL value is found.
Definition at line 653 of file shell.c.
References LOWEST_ARR_INDEX.
_wstderr()
void _wstderr (const char * s, bool use_perror)
Monkeypatch of perror and fprintf(stderr, ...). Needed due to "bad" management of some IDE/Shell terminals.
Parameters
s String to write to stderr.
use_perror Pass true to use perror(), pass false to use fwrite() to stderr. Do not pass true if errno wasn't set by the code throwing an error.
Definition at line 638 of file shell.c.
References TERMINAL_FLUSH_DELAY.
Referenced by execute_batch_file(), execute_cd(), execute_command(), execute_echo(), execute_external_cmd(), execute_status_monitor(), execute_stop_monitor(), redirect_stdin(), redirect_stdout(), restore_stdio(), and tokenize_single_command().
execute_batch_file()
void execute_batch_file (const char * path)
Tries to execute a certain (no comments, one line per command) batch file.
Parameters
path Path to the batch file.
Definition at line 329 of file shell.c.
References _wstderr(), and execute_command().
execute_cd()
void execute_cd (char * input, char ** sc_tokens, bool background_execution, char * cwd)
"Change directory" internal command.
Parameters
input Single command input.
sc_tokens Single command tokens.
background_execution Should be executed in the background?
cwd Current working directory. Used too as a buffer, where the new cd (if) will be saved.
Definition at line 415 of file shell.c.
References _wstderr(), cleanse_ampersand(), and ENV_OLDPWD_KEY.
Referenced by execute_command().
execute_command()
void execute_command (char * input, char * cwd)
Executes certain command, could be an internal one, external one, or unexistent.
Parameters
input Command input.
cwd Current working directory. This variable could be updated inside.
Definition at line 38 of file shell.c.
References _wstderr(), cleanse_newline(), cleanse_redirections_on_argv(), cleanse_redirections_on_sc(), CLR_ANSI_EC, delete_owned_metrics_json_config_file(), execute_cd(), execute_echo(), execute_external_cmd(), execute_status_monitor(), execute_stop_monitor(), get_metrics_json_config_file_path(), get_possible_redirection(), is_background_exec(), LOWEST_ARR_INDEX, MAX_SINGLE_COMMANDS, METRICS_APP_PATH, redirect_stdin(), redirect_stdout(), restore_stdio(), SC_TOKEN_SEPARATOR, and tokenize_single_command().
Referenced by execute_batch_file(), and start_shell_ml().
execute_echo()
void execute_echo (char * input, char ** sc_tokens, bool background_execution)
"Echo" internal command.
Parameters
input Single command input.
sc_tokens Single command tokens.
background_execution Should be executed in the background?
Definition at line 474 of file shell.c.
References _wstderr(), and cleanse_ampersand().
Referenced by execute_command().
execute_external_cmd()
void execute_external_cmd (char ** sc_tokens, bool background_execution)
Potential external command execution.
Parameters
sc_tokens Single command tokens.
background_execution Should be executed in the background?
Definition at line 584 of file shell.c.
References _wstderr(), LOWEST_ARR_INDEX, N_SINGALS_TO_HANDLE, and signals.
Referenced by execute_command().
execute_status_monitor()
void execute_status_monitor (const int * metrics_pid)
Executes the "status_monitor" command, that shows the "metrics" app, if it was init by this Shell.
Parameters
metrics_pid The "metrics" app process id.
Definition at line 527 of file shell.c.
References _wstderr(), handle_sigusr1(), METRICS_GET_STATUS_CODE, sfmh, and WAIT_T_FOR_METRICS_RESPONSE.
Referenced by execute_command().
execute_stop_monitor()
void execute_stop_monitor (int * metrics_pid)
Executes the "stop_monitor" command, which stops the "metrics" app, if it was init by this Shell.
Parameters
metrics_pid The "metrics" app process id.
Definition at line 511 of file shell.c.
References _wstderr().
Referenced by execute_command().
handle_sigusr1()
void handle_sigusr1 (int sig, siginfo_t * info, void * context)
You don't call this function directly, this is a handler.
Parameters
sig Not used inside the function.
info Metadata of the signal.
context Not used inside the function.
Index meaning (LSB to MSB): 0 - cpu_usage_percentage 1 - memory_used_percentage 2 - sectors_read_rate 3 - sectors_written_rate
Definition at line 604 of file shell.c.
References G_STATUS_N_METRICS_TRACKED, and sfmh.
Referenced by execute_status_monitor().
redirect_stdin()
int redirect_stdin (const char * file_name)
Redirects the stdin to a specific existent (hopefully) file.
Parameters
file_name Relative or absolute path to the file to which the stdin will be redirected.
Returns
-1 if no redirection was performed; otherwise returns the original file descriptor id.
Definition at line 351 of file shell.c.
References _wstderr().
Referenced by execute_command().
redirect_stdout()
int redirect_stdout (const char * file_name)
Redirects the stdout to a specific existent or inexistent (will get created) file.
Parameters
file_name Relative or absolute path to the file to which the stdout will be redirected. If it doesn't exist, will get created.
Returns
-1 if no redirection was performed; otherwise returns the original file descriptor id.
Definition at line 376 of file shell.c.
References _wstderr().
Referenced by execute_command().
restore_stdio()
void restore_stdio (int original_stdio, int target_fd)
Restores stdin to its original fd for the current process.
Parameters
original_stdio File descriptor id of the original stdin, or -1 (in which case this function does nothing)
target_fd Target file descriptor to set.
Definition at line 401 of file shell.c.
References _wstderr().
Referenced by execute_command().
tokenize_single_command()
char** tokenize_single_command (char * sc)
Passed a single command, tokenize it, and return an array with each token.
Parameters
sc Single command.
Returns
Array of tokens. Last "useful" element is always NULL. Must be manually freed after being used.
Definition at line 296 of file shell.c.
References _wstderr(), LOWEST_ARR_INDEX, MAX_TOKENS_PER_COMMAND, and TOKEN_SEPARATOR.
Referenced by execute_command().